# Generated by Django 5.2.13 on 2026-05-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='property',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
