# Generated by Django 5.2.13 on 2026-05-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_propertyimage_options'),
        ('listings', '0006_reservation'),
    ]

    operations = [
    ]
